/* =====================================================================
   EDITABLE CONTENT: READINGS, GAME_SCRIPT, QUIZ_ITEMS
   Change wording here; the logic below reads from these constants.
   ===================================================================== */

const READINGS = [
  { key:`clough`, chip:`Clough`, inText:`Clough (2015)`, short:`Principles of cybercrime, Chapter 1`,
    full:`Clough, J. (2015). Cybercrime. In Principles of cybercrime (2nd ed., pp. 3–27). Cambridge University Press. https://doi.org/10.1017/CBO9781139540803.002` },
  { key:`stalans`, chip:`Stalans & Donner`, inText:`Stalans and Donner (2018)`, short:`Explaining why cybercrime occurs`,
    full:`Stalans, L. J., & Donner, C. M. (2018). Explaining why cybercrime occurs: Criminological and psychological theories. In H. Jahankhani (Ed.), Cyber criminology (pp. 25–45). Springer. https://doi.org/10.1007/978-3-319-97181-0_2` },
  { key:`vakhitova`, chip:`Vakhitova`, inText:`Vakhitova (2024)`, short:`Cyber routine activity theory`,
    full:`Vakhitova, Z. (2024). Cyber routine activity theory. In H. Pontell (Ed.), Oxford research encyclopedia of criminology and criminal justice. Oxford University Press. https://doi.org/10.1093/acrefore/9780190264079.013.784` },
];

const GAME_SCRIPT = {
  landing: {
    title: `The CRAT Game`,
    tagline: `Walk one scam from three sides. See why cybercrime happens, and who can stop it.`,
    gameTile: { emoji:`🎭`, title:`Play the Game`, sub:`Offender, victim, guardian. About 6 minutes.` },
    quizTile: { emoji:`📝`, title:`Readings Quiz`, sub:`30 questions on the required readings.` },
    cites: `Clough (2015); Stalans and Donner (2018); Vakhitova (2024)`,
  },
  contentNote: {
    title: `Before you begin.`,
    text: `This game follows a fictional online scam. It touches on human trafficking and financial fraud. Nothing graphic is shown. If any of this is close to home, you can stop at any time. Support links are at the end of the game.`,
  },
  act1: {
    title: `Act 1: The Compound`,
    role: `You are the offender`,
    panels: [
      { caption:`Min, 23, needs work to support family back home. Min applies.`,
        ad:[`Customer service role overseas.`,`Great pay.`,`Free housing and flights.`] },
      { caption:`On arrival, Min's passport is "kept safe" by the managers. Min is told the flights and housing are a debt that must be worked off.` },
      { caption:`The job is not customer service. It is sending scam messages. The Foreman sets a daily quota. Min cannot leave.` },
    ],
    opener: {
      prompt: `Pick today's opening line.`,
      context: `The Foreman hands Min a rack of phones and a script book.`,
      options: [
        { id:`A`, text:`"Hi Mark, is dinner still on for Friday? 😊"`, tag:`the "wrong number" opener`, short:`'wrong number'`,
          feedback:`Friendly and low-pressure: this opener starts slow-burn relationship and 'investment' scams.` },
        { id:`B`, text:`"Your parcel is held at the depot. Pay $2.99 to release it: [link]"`, short:`'parcel'`,
          feedback:`Urgent and cheap: this opener aims for card details, fast.` },
        { id:`C`, text:`"Congratulations! You've been selected for a $500 gift card."`, short:`'gift card'`,
          feedback:`Too good to be true: many people spot it, but a few always don't.` },
      ],
      animLine: `The script barely matters. At this scale, a tiny reply rate is enough.`,
    },
    moment: {
      prompt: `Min has a moment alone with the phones.`,
      options: [
        { id:`A`, text:`Follow the script exactly.`, result:`Quota met. Min eats tonight.` },
        { id:`B`, text:`Slip a hint into one message: "Be careful who you trust online."`, result:`A supervisor reviews the chat logs. Min's 'debt' goes up. The hint is deleted before it is sent.` },
        { id:`C`, text:`Ask the Foreman to lower the quota.`, result:`The Foreman beats Min and doubles the quota.` },
      ],
    },
    story: {
      prompt: `Min tells themselves a story to get through the shift.`,
      options: [
        { id:`A`, text:`"I have no choice. The bosses make me do this."`, label:`denial of responsibility` },
        { id:`B`, text:`"They won't miss a few hundred dollars."`, label:`denial of injury` },
        { id:`C`, text:`"People who fall for this are greedy anyway."`, label:`denial of the victim` },
      ],
      labelPrefix: `Technique of neutralisation:`,
    },
    callout: { n:1, title:`A "motivated" offender?`,
      text:`Routine activity theory assumes offenders are rational and choose crime when benefits outweigh risks (Stalans & Donner, 2018). Min's motivation is coercion, not choice, and no parent, partner or friend (a handler) is close enough to steer Min away (Vakhitova, 2024). Meanwhile the internet acts as a force multiplier: one person can reach thousands (Clough, 2015).` },
    transition: `One reply arrives at 2:14 a.m. Its recipient is asleep in Brisbane. The conversation can wait.`,
  },
  act2: {
    title: `Act 2: The Wrong Number`,
    role: `You are the target`,
    intro: `You are Alex, 24, a university student in Brisbane. You've just moved into a new share house and have been feeling a bit lonely.`,
    /* One route per opening line picked in Act 1 (A = wrong number, B = parcel, C = gift card). */
    routes: {
      A: {
        title:`Act 2: The Wrong Number`, contact:`Daniel`,
        decisions: [
          { id:`D1`, contact:`Unknown number`,
            incoming:[ {type:`in`, who:`Unknown number`, text:`Hi Mark, is dinner still on for Friday? 😊`, time:`2:14 a.m.`}, {type:`sys`, text:`Alex sees it at 7:30 a.m.`} ],
            prompt:`A message from an unknown number. What do you do?`,
            options:[
              { id:`A`, text:`"Sorry, wrong number! Hope you find Mark 😄"`, reply:`Sorry, wrong number! Hope you find Mark 😄`, suit:1, gear:`access` },
              { id:`B`, text:`"Who is this?"`, reply:`Who is this?`, suit:1, gear:`access` },
              { id:`C`, text:`Block the number and forward the text to the scam-reporting number.`, action:`You blocked the number and forwarded the text to the scam-reporting number.`, guard:4, earlyExit:true },
            ] },
          { id:`D2`,
            incoming:[ {type:`in`, who:`Unknown number`, text:`Oops, so sorry! Wrong number. You sound nice though. Where are you based?`},
              {type:`sys`, text:`You chat for a while. Daniel, 29, says he imports wine in Melbourne.`},
              {type:`photos`}, {type:`in`, text:`This app keeps dropping messages. Can we chat on WhatsApp or Telegram instead?`} ],
            prompt:`Daniel wants to move the chat.`,
            options:[
              { id:`A`, text:`Move to the other app.`, action:`You moved the chat to the other app.`, suit:2, gear:`access`, note:`You've left the network where your telco's scam filters work.`, switchApp:true },
              { id:`B`, text:`Share your Instagram handle so he can "see you're real."`, action:`You shared your Instagram handle.`, suit:2, gear:`visibility` },
              { id:`C`, text:`Stay on SMS and keep it casual.`, reply:`Let's just keep chatting here 🙂`, guard:1 },
            ] },
          { id:`D3`,
            incoming:[ {type:`sys`, text:`Over the next few days Daniel messages every morning.`}, {type:`in`, text:`What are you saving for? Do you live alone?`} ],
            prompt:`Daniel asks about your life.`,
            options:[
              { id:`A`, text:`"Saving for a Europe trip, I've got about $6k put away. Yeah I pretty much keep to myself."`, reply:`Saving for a Europe trip, I've got about $6k put away. Yeah I pretty much keep to myself.`, suit:3, gear:`value`, inertia:`down`, note:`No one around to notice.` },
              { id:`B`, text:`"Oh, just the usual. I live with three friends, they're always around."`, reply:`Oh, just the usual. I live with three friends, they're always around.`, guard:1, inertia:`up` },
              { id:`C`, text:`"Why do you want to know that?"`, reply:`Why do you want to know that?`, guard:2 },
            ] },
          { id:`D4`, call:true,
            incoming:[ {type:`in`, text:`Let's video chat so you know I'm real!`} ],
            afterCall:[ {type:`in`, text:`Sorry, bad connection!`} ],
            prompt:`The call dropped. What do you make of it?`,
            options:[
              { id:`A`, text:`"Great, he's real!"`, reply:`Great, you're real! 😊`, guard:-1 },
              { id:`B`, text:`Ask him on the next call to turn his head side-on and hold up a note with today's date.`, action:`On the next call you asked Daniel to turn side-on and hold up a note with today's date.`, guard:2, show:`turn` },
              { id:`C`, text:`End the chat and reverse-image-search his photos.`, action:`You ended the chat and reverse-image-searched his photos.`, guard:3, show:`search` },
            ] },
          { id:`D5`,
            incoming:[ {type:`shot`}, {type:`in`, text:`My uncle taught me this crypto platform. Start with $500 and I'll guide you. You'll double it in a month.`} ],
            prompt:`The ask.`,
            options:[
              { id:`A`, text:`Send $500.`, action:`You sent $500 to the platform.`, suit:2, sent:true },
              { id:`B`, text:`Message your best friend Priya: "Does this seem legit?"`, action:`You messaged Priya: "Does this seem legit?"`, guard:2, follow:[{type:`priya`, text:`That's a scam, Alex. Please don't send anything.`}] },
              { id:`C`, text:`Look up the platform on the regulator's investor alert list.`, action:`You looked up the platform on the regulator's investor alert list.`, guard:3, follow:[{type:`sys`, text:`The platform is flagged as a scam.`}] },
            ] },
        ],
        call: {
          label:`Daniel · video`, speaker:`Daniel`, callLabel:`The video call`,
          captions:[ [0,`Hey! See, it's really me.`], [5,`Told you I'm real 😄`], [10,`Melbourne's freezing today.`], [15,`How's Brisbane?`] ],
          seconds:20, handAt:8, blinkAt:12,
          signs:`Watch for: skin that is too smooth, a shimmer at the jaw when a hand passes, lips a beat behind the voice, very little blinking.`,
        },
        turnNote:`As the face turns side-on, its edges smear and slip. The note with today's date never appears.`,
        searchNote:`Daniel's photos match a stock model's profile.`,
        endings: {
          near:{ title:`Near miss`, text:`You lost $500 and stopped. The 'platform' then asked for a $2,000 'withdrawal fee' to release your 'profits'. You didn't pay.` },
          hooked:{ title:`Hooked`, text:`The $500 'grew' on screen. You added your $6k savings. When you tried to withdraw, the platform froze your account and Daniel stopped replying.` },
        },
      },
      B: {
        title:`Act 2: The Parcel Text`, contact:`Caller`,
        intro:`You are Alex, 24, a university student in Brisbane. You've just moved into a new share house and have been shopping online to set up your new room.`,
        decisions: [
          { id:`D1`, contact:`Unknown number`,
            incoming:[ {type:`in`, who:`Unknown number`, text:`Your parcel is held at the depot. Pay $2.99 to release it: [link]`, time:`2:14 a.m.`}, {type:`sys`, text:`Alex sees it at 7:30 a.m. You are waiting on a delivery for the new share house.`} ],
            prompt:`A text about a parcel. What do you do?`,
            options:[
              { id:`A`, text:`Tap the link to see which parcel it is.`, action:`You tapped the link.`, suit:1, gear:`access` },
              { id:`B`, text:`"Which parcel? I'm expecting a few."`, reply:`Which parcel? I'm expecting a few.`, suit:1, gear:`access` },
              { id:`C`, text:`Block the number and forward the text to the scam-reporting number.`, action:`You blocked the number and forwarded the text to the scam-reporting number.`, guard:4, earlyExit:true },
            ] },
          { id:`D2`, contact:`Unknown number`,
            incoming:[ {type:`in`, who:`Unknown number`, text:`Your parcel will be returned to sender today. Complete your details here to release it.`}, {type:`site`} ],
            prompt:`The page asks for your details and card to pay $2.99.`,
            options:[
              { id:`A`, text:`Enter your card details and pay the $2.99.`, action:`You entered your card details and paid $2.99.`, suit:2, gear:`access`, note:`Your card number is now in the scammers' hands.` },
              { id:`B`, text:`Enter your name, address and date of birth, but stop at the payment page.`, action:`You entered your name, address and date of birth.`, suit:2, gear:`visibility` },
              { id:`C`, text:`Close the page and check the tracking number in the delivery company's own app.`, action:`You checked the delivery company's own app. There is no held parcel.`, guard:1 },
            ] },
          { id:`D3`, contact:`Caller`,
            incoming:[ {type:`sys`, text:`Next morning Alex's phone rings. The caller ID looks like the bank's number.`},
              {type:`in`, who:`Caller ("Bank fraud team")`, text:`Hi Alex, it's Sam from your bank's fraud team. We've blocked some suspicious payments on your card. How much is in your savings, and is anyone there with you?`} ],
            prompt:`The "bank" asks about your money and who is around.`,
            options:[
              { id:`A`, text:`"About $6k, for a Europe trip. No, I'm on my own."`, reply:`About $6k, for a Europe trip. No, I'm on my own.`, suit:3, gear:`value`, inertia:`down`, note:`No one around to notice.` },
              { id:`B`, text:`"My flatmates are here. I'll put you on speaker."`, reply:`My flatmates are here. I'll put you on speaker.`, guard:1, inertia:`up` },
              { id:`C`, text:`"Why do you need to know that?"`, reply:`Why do you need to know that?`, guard:2 },
            ] },
          { id:`D4`, contact:`Caller`,
            incoming:[ {type:`in`, who:`Caller ("Bank fraud team")`, text:`To prove I'm really from the bank, I've just sent you a code. Read it back to me and we'll secure your account.`},
              {type:`code`} ],
            prompt:`The caller wants the code.`,
            options:[
              { id:`A`, text:`Read the code out. "Great, it's really the bank."`, reply:`It's 4 8 1 … great, so you are the bank.`, guard:-1 },
              { id:`B`, text:`Say you'll call back and ask for the caller's staff ID and branch.`, reply:`I'll call you back. What's your staff ID and branch?`, guard:2, follow:[{type:`in`, who:`Caller ("Bank fraud team")`, text:`There's no time for that! Your money is at risk right now.`}] },
              { id:`C`, text:`Hang up and call the number on the back of your card.`, action:`You hung up and called the number on the back of your card.`, guard:3, follow:[{type:`sys`, text:`Your real bank has no record of any call.`}] },
            ] },
          { id:`D5`, contact:`Caller`,
            incoming:[ {type:`in`, who:`Caller ("Bank fraud team")`, text:`Your account is compromised. Move your savings into this safe account while we fix it. Do it now, and don't tell anyone, it could tip off the fraudsters.`} ],
            prompt:`The ask.`,
            options:[
              { id:`A`, text:`Move the money to the "safe account".`, action:`You started moving your savings to the "safe account".`, suit:2, sent:true },
              { id:`B`, text:`Message your best friend Priya: "Does this seem legit?"`, action:`You messaged Priya: "Does this seem legit?"`, guard:2, follow:[{type:`priya`, text:`That's a scam, Alex. Banks never ask you to move money. Please don't send anything.`}] },
              { id:`C`, text:`Look up "safe account" requests on Scamwatch.`, action:`You looked up "safe account" requests on Scamwatch.`, guard:3, follow:[{type:`sys`, text:`Scamwatch lists "safe account" requests as a common bank impersonation scam.`}] },
            ] },
        ],
        endings: {
          near:{ title:`Near miss`, text:`You moved $2,000 before your real bank paused the transfer and called you. You stopped there. Some of it may never come back.` },
          hooked:{ title:`Hooked`, text:`You moved your whole $6k into the 'safe account'. By the time you called your real bank, the money had gone offshore and the caller's number no longer worked.` },
        },
      },
      C: {
        title:`Act 2: The Prize`, contact:`Prize Centre`,
        intro:`You are Alex, 24, a university student in Brisbane. You've just moved into a new share house and have been shopping online to set up your new room.`,
        decisions: [
          { id:`D1`, contact:`Unknown number`,
            incoming:[ {type:`in`, who:`Unknown number`, text:`Congratulations! You've been selected for a $500 gift card.`, time:`2:14 a.m.`}, {type:`sys`, text:`Alex sees it at 7:30 a.m.`} ],
            prompt:`A prize you never entered for. What do you do?`,
            options:[
              { id:`A`, text:`"Really? How do I claim it?"`, reply:`Really? How do I claim it?`, suit:1, gear:`access` },
              { id:`B`, text:`"Who is this?"`, reply:`Who is this?`, suit:1, gear:`access` },
              { id:`C`, text:`Block the number and forward the text to the scam-reporting number.`, action:`You blocked the number and forwarded the text to the scam-reporting number.`, guard:4, earlyExit:true },
            ] },
          { id:`D2`, contact:`Prize Centre`,
            incoming:[ {type:`in`, who:`Prize Centre`, text:`We're the Prize Centre! 🎉 You were picked from thousands of numbers.`}, {type:`prize`},
              {type:`in`, who:`Prize Centre`, text:`To confirm you're a real winner, complete our quick survey or follow and share our page.`} ],
            prompt:`The Prize Centre wants to "confirm" you.`,
            options:[
              { id:`A`, text:`Fill in the survey: name, email, birthday and phone.`, action:`You filled in the survey.`, suit:2, gear:`access` },
              { id:`B`, text:`Follow the page and share the post on your public profile.`, action:`You followed the page and shared the post publicly.`, suit:2, gear:`visibility` },
              { id:`C`, text:`Keep it to SMS and don't share any details.`, reply:`I'd rather not share anything. Just tell me how it works.`, guard:1 },
            ] },
          { id:`D3`, contact:`Prize Centre`,
            incoming:[ {type:`sys`, text:`The Prize Centre messages every morning with a countdown to "claim day".`},
              {type:`in`, who:`Prize Centre`, text:`So we can plan delivery: what are you saving for? And do you live alone, in case the courier needs someone to sign?`} ],
            prompt:`The Prize Centre asks about your life.`,
            options:[
              { id:`A`, text:`"Saving for a Europe trip, I've got about $6k put away. I'm usually home on my own."`, reply:`Saving for a Europe trip, I've got about $6k put away. I'm usually home on my own.`, suit:3, gear:`value`, inertia:`down`, note:`No one around to notice.` },
              { id:`B`, text:`"I live with three friends, someone's always home."`, reply:`I live with three friends, someone's always home.`, guard:1, inertia:`up` },
              { id:`C`, text:`"Why do you want to know that?"`, reply:`Why do you want to know that?`, guard:2 },
            ] },
          { id:`D4`, call:true, contact:`Prize Centre`,
            incoming:[ {type:`in`, who:`Prize Centre`, text:`Still not sure? Watch this video from last month's winner!`} ],
            afterCall:[ {type:`in`, who:`Prize Centre`, text:`Now it's your turn! 🎁`} ],
            prompt:`The video ends. What do you make of it?`,
            options:[
              { id:`A`, text:`"Great, it's real!"`, reply:`Great, it's real! 😊`, guard:-1 },
              { id:`B`, text:`Replay the video slowly and watch the jaw and the lips.`, action:`You replayed the video slowly.`, guard:2, show:`turn` },
              { id:`C`, text:`Reverse-image-search the "winner's" photo.`, action:`You reverse-image-searched the winner's photo.`, guard:3, show:`search` },
            ] },
          { id:`D5`, contact:`Prize Centre`,
            incoming:[ {type:`in`, who:`Prize Centre`, text:`Last step! Pay the $49.95 delivery and processing fee and your $500 gift card is on its way. Offer ends in 1 hour ⏰`} ],
            prompt:`The ask.`,
            options:[
              { id:`A`, text:`Pay the $49.95 fee.`, action:`You paid the $49.95 fee.`, suit:2, sent:true },
              { id:`B`, text:`Message your best friend Priya: "Does this seem legit?"`, action:`You messaged Priya: "Does this seem legit?"`, guard:2, follow:[{type:`priya`, text:`That's a scam, Alex. Real prizes don't charge a fee. Please don't send anything.`}] },
              { id:`C`, text:`Search the "Prize Centre" on Scamwatch.`, action:`You searched the "Prize Centre" on Scamwatch.`, guard:3, follow:[{type:`sys`, text:`Upfront fees for prizes you never entered for are a well-known scam.`}] },
            ] },
        ],
        call: {
          label:`Last month's "winner" · video`, speaker:`"Winner"`, callLabel:`The winner video`, scene:`beach`, skipLabel:`Skip to the end of the video`,
          captions:[ [0,`Hi! I won $500 last month!`], [5,`It took two minutes, honestly.`], [10,`I paid the small fee and it arrived next day.`], [15,`Don't miss out!`] ],
          seconds:20, handAt:8, blinkAt:12,
          signs:`Watch for: skin that is too smooth, a shimmer at the jaw when a hand passes, lips a beat behind the voice, very little blinking.`,
        },
        turnNote:`Slowed down, the face smears at the edges and the lips run a beat behind the words.`,
        searchNote:`The "winner's" photo matches a stock model's profile.`,
        endings: {
          near:{ title:`Near miss`, text:`You paid $49.95 and stopped. Then a $300 'customs charge' appeared before the gift card could be 'released'. You didn't pay.` },
          hooked:{ title:`Hooked`, text:`You paid the fee, then a 'customs charge', then an 'insurance bond'. Your $6k savings went piece by piece, and the gift card never came.` },
        },
      },
    },
    protectedEnding:{ title:`Protected`, text:`You hardened the target. The script moved on to the next of 2,000 numbers.` },
    replayLabel:`Replay as a more trusting Alex`,
    callout: { n:2, title:`Convergence without co-presence.`,
      text:`Alex and Min never shared a place or even a moment: the message waited hours on a network. Reyns and colleagues argue networks act as the "place" of convergence, and that convergence happens when the victim experiences the act (Vakhitova, 2024). Visibility (photos, handles, public profiles) is the target feature with the most consistent support in cybercrime research (Stalans & Donner, 2018).` },
  },
  act3: {
    title: `Act 3: Guardian Square`,
    role: `You are the bystander`,
    intro: `Someone like Alex is being targeted right now. You have three brass tokens. Place them on the guardians you think can do the most to stop this scam.`,
    guardians: [
      { id:`priya`, icon:`priya`, name:`Priya, Alex's best friend`, short:`Priya`, value:2, role:`Capable guardian (informal)`,
        can:`Notice changes in Alex, say "that's a scam", sit with Alex while they call the bank.`, limit:`Only helps if Alex talks to her.` },
      { id:`bank`, icon:`bank`, name:`Alex's bank fraud team`, short:`the bank`, value:2, role:`Place manager / guardian over the payment channel`,
        can:`Flag unusual payments, pause transfers, attempt recalls.`, limit:`Speed matters; crypto transfers are hard to reverse.` },
      { id:`telco`, icon:`telco`, name:`Alex's phone company (telco)`, short:`the telco`, value:2, role:`Place manager of the network`,
        can:`Filter and block scam SMS at scale, act on forwarded scam texts.`, limit:`Loses sight once the chat moves to another app.` },
      { id:`platform`, icon:`platform`, name:`The messaging platform's trust and safety team`, short:`the platform`, value:1.5, role:`Cyber place manager`,
        can:`Remove fake accounts, detect mass-messaging patterns.`, limit:`The same operation opens new accounts daily.` },
      { id:`scamwatch`, icon:`scamwatch`, name:`Scamwatch and the National Anti-Scam Centre`, short:`Scamwatch`, value:1.5, role:`Super controller`,
        can:`Issue public warnings, share scam intelligence with banks, telcos and platforms, pressure them to act.`, limit:`It shapes others' incentives rather than intervening in one chat.` },
      { id:`afp`, icon:`afp`, name:`ReportCyber and the Australian Federal Police`, short:`the AFP`, value:1, role:`Formal guardian / law enforcement`,
        can:`Collect reports, investigate, work with international partners.`, limit:`The offenders are offshore; evidence crosses many jurisdictions and extradition is slow.` },
      { id:`esafety`, icon:`esafety`, name:`eSafety Commissioner`, short:`eSafety`, value:0.5, role:`Regulator for online safety harms (image-based abuse, cyberbullying, adult cyber abuse)`,
        can:`Act if the scam turns into sextortion or image-based abuse.`, limit:`Financial scams are outside its main remit, so it is the right guardian only if the harm changes shape.` },
    ],
    handler: { name:`Min's family (handler)`, note:`Too far away to reach Min. Handlers work on offenders, not targets.` },
    results: [
      { min:5, text:`Strong layered defence: you broke the triangle at more than one corner.` },
      { min:3.5, text:`Good cover, but most of your guardians act after the harm.` },
      { min:-1, text:`Your guardians are important, but mostly slow or far from the moment of harm.` },
    ],
    esafetyNote:`eSafety lights only half a segment: financial scams are outside its main remit, so it helps only if the harm changes shape.`,
    zoom: { guardians:`Guardians protect the target`, place:`Place managers control the online places`, handlers:`Handlers control the offender`, super:`Super controllers set the incentives for all of them` },
    callout: { n:3, title:`Guardianship online is active, not passive.`,
      text:`Offline, a bystander's mere presence can deter crime. Online, third parties are usually invisible and users are anonymous, so guardianship depends on someone acting: reporting, blocking, warning (Vakhitova, 2024). Much of the internet's infrastructure is privately owned, so guardianship is shared across banks, telcos, platforms and ISPs, not just police (Clough, 2015).` },
  },
  map: {
    title: `Your CRAT Map`,
    support: `If you or someone you know has been scammed, contact your bank straight away, then report it at scamwatch.gov.au or cyber.gov.au. IDCARE (idcare.org) offers free support. If you are feeling distressed, Lifeline is available on 13 11 14.`,
  },
  discussion: {
    title: `Act 4: Class Discussion`,
    prompts: [
      { title:`Is Min a "motivated offender"?`, text:`Routine activity theory assumes rational, self-interested offenders. What happens to the theory when the offender is a trafficking victim? Who is the real motivated offender here?` },
      { title:`Where and when did the crime happen?`, text:`Alex and Min were never online at the same moment. Using Reyns and colleagues' argument (in Vakhitova, 2024), explain where and when convergence occurred.` },
      { title:`Guardianship or target hardening?`, text:`Is Alex's scam filter, reverse image search or antivirus a form of guardianship, or does it just make Alex a less suitable target? Take a side (Vakhitova, 2024).` },
      { title:`Who should pay?`, text:`Alex, the bank, the telco, the platform or government? Use the idea of super controllers and incentives.` },
      { title:`Why don't victims report?`, text:`Using Clough (2015), list reasons Alex might stay silent, and what that does to crime statistics.` },
      { title:`Does CRAT blame victims?`, text:`Focusing on "suitable targets" can sound like victim-blaming, and the theory is criticised for ignoring social inequality (Vakhitova, 2024). Is this fair? What would you add?` },
    ],
  },
};

/* Each option: [letter, option text, explanation]. `answer` is the correct letter. */
const QUIZ_ITEMS = [
  { reading:`clough`, cite:`(Clough, 2015, p. 3)`, answer:`A`,
    question:`Clough opens with the RBS WorldPay case, in which counterfeit payroll cards were used to withdraw over US$9 million from ATMs in 280+ cities in under 12 hours. Which set of features does the case illustrate about modern cybercrime?`,
    options:[
      [`A`,`Organised, financially motivated, technologically sophisticated and transnational.`,`Correct. Clough uses the case to show exactly these four features of modern cybercrime.`],
      [`B`,`Opportunistic, curiosity-driven, low-skill and local.`,`Incorrect: the case was carefully planned, profit-driven, highly technical and spread across many countries.`],
      [`C`,`Politically motivated and aimed at critical infrastructure.`,`Incorrect: the motive was money; nothing suggests a political or terrorist aim.`],
      [`D`,`Committed by a lone insider without any use of networks.`,`Incorrect: it involved a hacking conspiracy and a worldwide network of "cashers".`]]},
  { reading:`clough`, cite:`(Clough, 2015, pp. 10–11)`, answer:`B`,
    question:`Using Clough's classification, how is an SMS "investment" scam like the one in the game best described?`,
    options:[
      [`A`,`Cyber-dependent crime.`,`Incorrect: cyber-dependent crimes can only be committed with ICT and usually target the technology itself, such as hacking or malware.`],
      [`B`,`Cyber-enabled crime.`,`Correct. Fraud is a traditional crime; ICT increases its scale and reach, but fraud can also be committed without technology.`],
      [`C`,`Computer-supported crime.`,`Incorrect: here the technology is central to committing the offence, not merely a store of evidence.`],
      [`D`,`Cyberterrorism.`,`Incorrect: there is no political, religious or ideological aim and no attack on critical infrastructure.`]]},
  { reading:`clough`, cite:`(Clough, 2015, p. 11)`, answer:`C`,
    question:`What does Clough mean by a "computer-supported crime"?`,
    options:[
      [`A`,`A crime where the computer is the target, such as a denial of service attack.`,`Incorrect: that describes a cyber-dependent crime.`],
      [`B`,`A traditional crime scaled up by networks, such as online fraud.`,`Incorrect: that describes a cyber-enabled crime.`],
      [`C`,`A crime where computer use is incidental but may hold evidence, such as a suspect's saved messages.`,`Correct. The technology is a repository of evidence rather than a means of committing the offence.`],
      [`D`,`Any crime committed inside a virtual world such as Second Life.`,`Incorrect: Clough treats "virtual crimes" separately and argues the relevant conduct still happens in the physical world.`]]},
  { reading:`clough`, cite:`(Clough, 2015, p. 6)`, answer:`B`,
    question:`Clough says the internet acts as a "force multiplier". What does this mean?`,
    options:[
      [`A`,`Police can multiply their surveillance powers online.`,`Incorrect: Clough stresses that networks make surveillance harder, not easier.`],
      [`B`,`Offenders can reach far more victims, cheaply, and automate the process, at a scale not possible offline.`,`Correct. He gives the Bredolab botnet, estimated to send 3 billion emails a day, as an example.`],
      [`C`,`Each online offence carries a multiplied penalty.`,`Incorrect: the term describes offender reach, not sentencing.`],
      [`D`,`Victims are harmed more deeply online than offline.`,`Incorrect: the term is about volume and reach, not the depth of harm.`]]},
  { reading:`clough`, cite:`(Clough, 2015, pp. 8–9)`, answer:`B`,
    question:`Clough applies routine activity theory to the online environment. Which statement matches his argument about capable guardians?`,
    options:[
      [`A`,`Police alone can and should act as guardians online.`,`Incorrect: he argues it is neither practical nor desirable for police to be everywhere.`],
      [`B`,`Guardianship is shared across the community, and ISPs are especially significant as gatekeepers of data.`,`Correct. Parents, banks, system administrators, industry and regulators all play a role, with ISPs particularly important.`],
      [`C`,`Guardians are unnecessary online because encryption protects everyone.`,`Incorrect: he lists encryption as something that helps offenders conceal activity.`],
      [`D`,`Guardianship online is stronger than offline because every action leaves a trace.`,`Incorrect: he highlights volatile evidence, multiple jurisdictions and private infrastructure as barriers to detection.`]]},
  { reading:`clough`, cite:`(Clough, 2015, p. 9)`, answer:`D`,
    question:`Drawing on Lessig, Clough says effective regulation of cybercrime must address four "modalities of constraint". Which of these is NOT one of the four?`,
    options:[
      [`A`,`The law.`,`Incorrect: law is one of Lessig's four modalities.`],
      [`B`,`Architecture (code).`,`Incorrect: architecture is one of the four.`],
      [`C`,`Social norms.`,`Incorrect: social norms are one of the four.`],
      [`D`,`International treaties.`,`Correct. The four are law, architecture, social norms and the market. Treaties are a form of law, not a separate modality.`]]},
  { reading:`clough`, cite:`(Clough, 2015, pp. 17–18)`, answer:`A`,
    question:`What is the principle of "online/offline consistency"?`,
    options:[
      [`A`,`Online conduct should, as far as possible, be regulated the same way as offline conduct, relying on existing laws where they work.`,`Correct. New offences are created only where needed, so the online world is not less regulated than the offline one.`],
      [`B`,`Every offline crime needs a separate new online offence.`,`Incorrect: this is the opposite of the principle.`],
      [`C`,`Online conduct should be regulated more lightly to protect innovation.`,`Incorrect: the principle aims to stop the online world becoming a less regulated haven for crime.`],
      [`D`,`Offences should be limited formally to the online environment.`,`Incorrect: Clough says such limits should mostly be avoided.`]]},
  { reading:`clough`, cite:`(Clough, 2015, p. 8)`, answer:`B`,
    question:`According to the UN study Clough cites, how common is a transnational element in cybercrime encountered by police?`,
    options:[
      [`A`,`Rare: under 5 per cent of cases in most countries.`,`Incorrect: the study found the opposite.`],
      [`B`,`Over half of responding countries reported that between 50 and 100 per cent of cybercrime acts involved a transnational element.`,`Correct. This is why global reach is such a challenge for law enforcement.`],
      [`C`,`Only relevant for cyberterrorism.`,`Incorrect: the figure refers to cybercrime generally.`],
      [`D`,`Unknown, because police do not record where offenders are.`,`Incorrect: the study did report a figure, even though statistics have limits.`]]},
  { reading:`clough`, cite:`(Clough, 2015, p. 20)`, answer:`B`,
    question:`Clough (drawing on Kerr) contrasts "internal" and "external" perspectives of online conduct. Which describes the external perspective?`,
    options:[
      [`A`,`How the user experiences entering an online world separate from where they sit.`,`Incorrect: that is the internal perspective.`],
      [`B`,`The viewpoint of an outsider observing what the computer actually does in the physical world.`,`Correct. From this view, a "virtual rape" is a transmission of distressing electronic communications, which is what the criminal law responds to.`],
      [`C`,`The view of a foreign court exercising jurisdiction.`,`Incorrect: the distinction is about perspective on conduct, not jurisdiction.`],
      [`D`,`The platform's terms of service.`,`Incorrect: the rules of a game are one relevant factor but are not the "external perspective".`]]},
  { reading:`clough`, cite:`(Clough, 2015, pp. 24–26)`, answer:`B`,
    question:`What was the first binding multinational instrument to address cybercrime?`,
    options:[
      [`A`,`The UN Comprehensive Study on Cybercrime (2013).`,`Incorrect: this was a study, not a binding agreement.`],
      [`B`,`The Council of Europe Convention on Cybercrime (Budapest, 2001).`,`Correct. It came into force in 2004 and, although regional, was intended to apply globally; Australia and the United States are parties.`],
      [`C`,`The Computer Misuse Act 1990 (UK).`,`Incorrect: this is domestic legislation in one country.`],
      [`D`,`The Twelfth UN Congress on Crime Prevention (2010).`,`Incorrect: countries there could not agree on a new global convention.`]]},

  { reading:`stalans`, cite:`(Stalans & Donner, 2018, pp. 28–29)`, answer:`D`,
    question:`Cohen and Felson's routine activity theory says criminal opportunities arise when three elements converge in time and space. Which of the following is NOT one of them?`,
    options:[
      [`A`,`A motivated offender.`,`Incorrect: this is one of the three elements.`],
      [`B`,`A suitable target.`,`Incorrect: this is one of the three elements.`],
      [`C`,`A lack of capable guardianship.`,`Incorrect: this is one of the three elements.`],
      [`D`,`The offender's low self-control.`,`Correct. Low self-control comes from Gottfredson and Hirschi's general theory of crime, a separate theory.`]]},
  { reading:`stalans`, cite:`(Stalans & Donner, 2018, p. 29)`, answer:`A`,
    question:`Yar (2005) was critical of applying routine activity theory to cyberspace. Which target characteristics did he say are hard to translate online?`,
    options:[
      [`A`,`Value and inertia.`,`Correct. Digital targets have little physical resistance to removal, and value is hard to measure.`],
      [`B`,`Visibility and accessibility.`,`Incorrect: these translate quite readily; visibility has the most empirical support.`],
      [`C`,`Certainty and severity.`,`Incorrect: these are features of punishment in deterrence theory, not target characteristics.`],
      [`D`,`Anonymity and depersonalisation.`,`Incorrect: these are features of the internet environment, not target characteristics in routine activity theory.`]]},
  { reading:`stalans`, cite:`(Stalans & Donner, 2018, p. 29)`, answer:`C`,
    question:`In Leukfeldt and Yar's (2016) analysis of 9,161 Dutch citizens, which routine activity element predicted victimisation across the widest range of cybercrimes?`,
    options:[
      [`A`,`Value.`,`Incorrect: financial value was not a significant predictor.`],
      [`B`,`Inertia.`,`Incorrect: inertia was not measured.`],
      [`C`,`Visibility.`,`Correct. More than half of the visibility measures predicted malware, consumer fraud and cyberthreat victimisation.`],
      [`D`,`Antivirus software.`,`Incorrect: antivirus was found to be unrelated to victimisation.`]]},
  { reading:`stalans`, cite:`(Stalans & Donner, 2018, p. 30)`, answer:`B`,
    question:`What have studies found about antivirus software as a form of capable guardianship?`,
    options:[
      [`A`,`It strongly reduces all forms of cyber victimisation.`,`Incorrect: this is not supported by the research reviewed.`],
      [`B`,`It has generally been unrelated, and sometimes positively related, to cyber victimisation.`,`Correct. This is one reason the authors describe support for guardianship as mixed.`],
      [`C`,`It eliminates malware but not fraud.`,`Incorrect: no study reviewed found it eliminated any crime type.`],
      [`D`,`It has never been tested.`,`Incorrect: several studies, including Leukfeldt and Yar (2016) and Ngo and Paternoster (2011), tested it.`]]},
  { reading:`stalans`, cite:`(Stalans & Donner, 2018, p. 30)`, answer:`A`,
    question:`According to Leukfeldt and Yar (2016), which kind of guardianship reduced the likelihood of stalking or hacking victimisation?`,
    options:[
      [`A`,`Greater awareness of online risks.`,`Correct. Awareness reduced the likelihood of these two types of victimisation.`],
      [`B`,`Higher computer skills.`,`Incorrect: computer skills have generally been unrelated to harassment victimisation.`],
      [`C`,`Spending more time online.`,`Incorrect: more time online increases exposure, and with it the risk of fraud and malware.`],
      [`D`,`Using social networking sites more often.`,`Incorrect: this increases exposure to motivated offenders.`]]},
  { reading:`stalans`, cite:`(Stalans & Donner, 2018, p. 30)`, answer:`B`,
    question:`How do Stalans and Donner sum up the overall empirical support for routine activity theory in explaining cybercrime?`,
    options:[
      [`A`,`Strong and consistent across all elements.`,`Incorrect: findings on value and guardianship were mixed or null.`],
      [`B`,`Limited support, with visibility having the most support across cybercrime types.`,`Correct. This is their overall conclusion.`],
      [`C`,`No support at all.`,`Incorrect: visibility and time online were repeatedly linked to victimisation.`],
      [`D`,`Support only for hacking.`,`Incorrect: visibility predicted several crime types, including fraud and malware.`]]},
  { reading:`stalans`, cite:`(Stalans & Donner, 2018, p. 27)`, answer:`B`,
    question:`In deterrence research, which aspect of punishment has been most consistently associated with a (modest) deterrent effect?`,
    options:[
      [`A`,`Severity of punishment.`,`Incorrect: severity has been less consistently linked to deterrence.`],
      [`B`,`Certainty of detection.`,`Correct. This matters for cybercrime, where the chance of being caught is often low.`],
      [`C`,`Celerity (swiftness) of punishment.`,`Incorrect: celerity has been less consistently linked to deterrence.`],
      [`D`,`Public shaming.`,`Incorrect: this is not one of Beccaria's three elements.`]]},
  { reading:`stalans`, cite:`(Stalans & Donner, 2018, p. 28)`, answer:`B`,
    question:`Kigerl's (2015) study of the US CAN-SPAM Act found spammers sent less spam but complied less with email header rules to avoid detection. What does this support?`,
    options:[
      [`A`,`Absolute deterrence: offenders stop offending.`,`Incorrect: spammers kept offending.`],
      [`B`,`Restrictive deterrence: offenders limit how often they offend and adapt to avoid detection.`,`Correct. Gibbs (1975) coined the term.`],
      [`C`,`General strain theory.`,`Incorrect: the finding concerns responses to legal threat, not strain.`],
      [`D`,`Social learning theory.`,`Incorrect: it is about reactions to law, not learning from peers.`]]},
  { reading:`stalans`, cite:`(Stalans & Donner, 2018, p. 36)`, answer:`B`,
    question:`Stalans and Donner list features of the internet environment that may facilitate cybercrime. Which feature describes perpetrators lacking knowledge of the people affected and the consequences for them?`,
    options:[
      [`A`,`Perceived anonymity.`,`Incorrect: this is about the offender's identity being hidden.`],
      [`B`,`Depersonalisation of targets or victims.`,`Correct. Not knowing the victim can ease moral disengagement, as with Min sending messages to numbers, not people.`],
      [`C`,`Amorphous geographical boundaries.`,`Incorrect: this is about crossing jurisdictions.`],
      [`D`,`Ease of affiliation.`,`Incorrect: this is about finding like-minded offenders online.`]]},
  { reading:`stalans`, cite:`(Stalans & Donner, 2018, pp. 34–35)`, answer:`C`,
    question:`A scam compound worker thinks: "I have no choice. The bosses make me do this." Which of Sykes and Matza's techniques of neutralisation does this reflect?`,
    options:[
      [`A`,`Denial of injury.`,`Incorrect: that minimises the harm done, for example "they won't miss the money".`],
      [`B`,`Denial of the victim.`,`Incorrect: that claims the victim deserved it, for example "they're greedy".`],
      [`C`,`Denial of responsibility.`,`Correct. It shifts blame to circumstances or third parties. For a trafficked worker, the claim may also be true, which is worth discussing.`],
      [`D`,`Appeal to higher loyalties.`,`Incorrect: that claims the act serves a more important value or group.`]]},

  { reading:`vakhitova`, cite:`(Vakhitova, 2024)`, answer:`B`,
    question:`Routine activity theory and CRAT are "situational" rather than "dispositional" theories. What does that mean?`,
    options:[
      [`A`,`They explain why some people have a disposition to offend.`,`Incorrect: that is what dispositional theories do.`],
      [`B`,`They take criminal inclination as given and focus on the situations in which people decide whether to act on it.`,`Correct. The focus is opportunity, not criminality.`],
      [`C`,`They explain crime by a person's location on a map.`,`Incorrect: "situational" refers to social situations, not just geography.`],
      [`D`,`They focus on the victim's personality.`,`Incorrect: they focus on the convergence of offender, target and guardian.`]]},
  { reading:`vakhitova`, cite:`(Vakhitova, 2024)`, answer:`B`,
    question:`Yar argued cyberspace is "spatio-temporally disorganised", so offenders and victims need not meet. How did Reyns and colleagues (2011) respond?`,
    options:[
      [`A`,`They agreed and abandoned routine activity theory for cybercrime.`,`Incorrect: they adapted it instead.`],
      [`B`,`Networks act as virtual places where convergence happens, and convergence occurs over time, when the victim experiences the act.`,`Correct. This is how Alex and Min "converged" hours apart.`],
      [`C`,`Convergence only happens when both parties are online at the same instant.`,`Incorrect: this ignores asynchronous communication such as email and text.`],
      [`D`,`Convergence is irrelevant because offenders pick victims at random.`,`Incorrect: they argued certain situations make convergence more likely.`]]},
  { reading:`vakhitova`, cite:`(Vakhitova, 2024)`, answer:`B`,
    question:`Why does a guardian's mere presence deter crime less online than offline?`,
    options:[
      [`A`,`Online users are always more willing to intervene.`,`Incorrect: this does not explain a weaker effect of presence.`],
      [`B`,`Third parties are often invisible online and users are anonymous, so passive presence does not raise the offender's perceived risk.`,`Correct. Online guardianship therefore relies on active intervention.`],
      [`C`,`Offenders online are not rational.`,`Incorrect: CRAT keeps the assumption of rational offenders.`],
      [`D`,`There are fewer people online than offline.`,`Incorrect: billions of people are online.`]]},
  { reading:`vakhitova`, cite:`(Vakhitova, 2024)`, answer:`A`,
    question:`Capable cyber guardianship has been redefined as multidimensional. Which three dimensions are usually included?`,
    options:[
      [`A`,`Personal (literacy and awareness), technical (security software) and active intervention by human third parties.`,`Correct. This is the multidimensional view.`],
      [`B`,`Value, inertia and visibility.`,`Incorrect: these describe target suitability (VIVA).`],
      [`C`,`Handlers, place managers and super controllers.`,`Incorrect: these are other types of crime controller, not dimensions of guardianship.`],
      [`D`,`Certainty, severity and celerity.`,`Incorrect: these are elements of deterrence.`]]},
  { reading:`vakhitova`, cite:`(Vakhitova, 2024)`, answer:`B`,
    question:`Hollis et al. (2013) and Vakhitova and Reynald (2014) argue that antivirus software, firewalls and personal security habits are not really guardianship. What do they say these are?`,
    options:[
      [`A`,`Handlers.`,`Incorrect: handlers control offenders through emotional ties.`],
      [`B`,`Target hardening, which reduces a target's suitability.`,`Correct. They make a target less suitable but do not make a guardian more present or capable.`],
      [`C`,`Super controllers.`,`Incorrect: super controllers shape the incentives of other controllers.`],
      [`D`,`Place managers.`,`Incorrect: place managers control online places, such as moderators.`]]},
  { reading:`vakhitova`, cite:`(Vakhitova, 2024)`, answer:`B`,
    question:`In CRAT, who best fits the role of a cyber place manager?`,
    options:[
      [`A`,`A victim's best friend who warns them about a scam.`,`Incorrect: that is a capable guardian through active intervention.`],
      [`B`,`Website administrators, developers and moderators who set and enforce rules in their online spaces.`,`Correct. They have the most control over activity within their domains.`],
      [`C`,`An offender's parent.`,`Incorrect: that is a handler.`],
      [`D`,`The media.`,`Incorrect: the media is an example of a super controller.`]]},
  { reading:`vakhitova`, cite:`(Vakhitova, 2024)`, answer:`B`,
    question:`What is a handler in CRAT?`,
    options:[
      [`A`,`Someone who protects the target.`,`Incorrect: that is a guardian.`],
      [`B`,`Someone with an emotional connection to a potential offender, such as a parent, partner or friend, who can steer them away from crime.`,`Correct. In the game, Min's family are handlers, but too far away to act.`],
      [`C`,`The platform that hosts the offender's messages.`,`Incorrect: that is a place manager.`],
      [`D`,`The police officer who handles the case.`,`Incorrect: police act as formal guardians.`]]},
  { reading:`vakhitova`, cite:`(Vakhitova, 2024)`, answer:`B`,
    question:`Sampson et al. (2010) introduced "super controllers". Which of these is an example in cyberspace?`,
    options:[
      [`A`,`A single user who installs a firewall.`,`Incorrect: that is target hardening or self-guardianship.`],
      [`B`,`Entities such as ISPs, regulators, cybersecurity agencies, internet governance bodies and large tech companies that shape the incentives of other controllers.`,`Correct. They influence whether guardians, handlers and place managers act effectively.`],
      [`C`,`The victim's flatmates.`,`Incorrect: they are potential capable guardians.`],
      [`D`,`The offender.`,`Incorrect: super controllers regulate controllers, not offenders directly.`]]},
  { reading:`vakhitova`, cite:`(Vakhitova, 2024)`, answer:`B`,
    question:`Buil-Gil et al. found a surge in cyber-enabled romance fraud during the COVID-19 pandemic, beyond what earlier data predicted. How does Vakhitova link this to routine activity theory?`,
    options:[
      [`A`,`It shows offender motivation increased during the pandemic.`,`Incorrect: the explanation focuses on changes in routines, not offender motivation.`],
      [`B`,`Rapid social change (more reliance on the internet and more loneliness) created new criminal opportunities, echoing Cohen and Felson's explanation of post-WWII crime trends.`,`Correct. Changes in routine activities change opportunities.`],
      [`C`,`It shows guardianship does not matter.`,`Incorrect: the study was about opportunity created by changed routines.`],
      [`D`,`It disproves CRAT at the macro level.`,`Incorrect: Vakhitova presents it as support.`]]},
  { reading:`vakhitova`, cite:`(Vakhitova, 2024)`, answer:`B`,
    question:`Some studies found that people with antivirus software were more likely to report being hacked. What limitation does Vakhitova say may explain this?`,
    options:[
      [`A`,`Antivirus software attracts hackers.`,`Incorrect: no mechanism supports this.`],
      [`B`,`Reverse causality in cross-sectional data: people may install antivirus after being victimised.`,`Correct. Cross-sectional studies often cannot establish which came first.`],
      [`C`,`Too few people were surveyed.`,`Incorrect: the issue is study design, not sample size.`],
      [`D`,`Lifestyle Exposure Theory was used instead of CRAT.`,`Incorrect: mixing theories is a separate criticism she raises.`]]},
];
